app = "que-morfamos-api-black-paper-1056"
primary_region = "gru"  # <--- CAMBIADO de 'gru' a 'eze' (Buenos Aires)

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"   # "stop" apaga después de idle, "suspend" es más rápido para retomar
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    soft_limit = 50    # Permite más requests concurrentes antes de escalar
    hard_limit = 100



  [[http_service.checks]]
    grace_period = "60s"   # <--- Aumentado a 60s por las dudas (Pandas es pesado)
    interval = "30s"
    method = "get"
    path = "/health"
    timeout = "10s"

[[vm]]
  memory_mb = 768
  cpu_kind = "shared"
  cpus = 1
