# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          COMMIT_DATE=$(git show -s --format=%cI "$GITHUB_SHA")
          flyctl deploy --remote-only --build-arg BACKEND_UPDATED_AT="$COMMIT_DATE"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
